#!/usr/bin/env python3
"""
Logisim driver: calibrate and drive switches+strobe in Logisim using pyautogui.

Usage:
  python tools/logisim_driver.py calibrate   # interactively record SW0..SW7 and STROBE positions
  python tools/logisim_driver.py run seq.txt # play an input_sequence file generated by type_to_logisim

Notes:
- Ensure Logisim window is visible and not moved during playback.
- Before running `run`, set all switches to OFF (0) to ensure predictable behavior.
- Install pyautogui: `pip install pyautogui`
"""

import sys
import time
import json
from pathlib import Path

try:
    import pyautogui
except Exception as e:
    print('pyautogui is required. Install with: pip install pyautogui')
    raise

LAYOUT_PATH = Path(__file__).resolve().parent / 'logisim_layout.json'


def calibrate(out=LAYOUT_PATH):
    print('Calibration: you will be asked to hover the mouse over each item and press Enter.')
    items = ['SW0','SW1','SW2','SW3','SW4','SW5','SW6','SW7','STROBE']
    coords = {}
    for name in items:
        input(f"Place mouse over {name} in Logisim and press Enter...")
        x,y = pyautogui.position()
        coords[name] = [x,y]
        print(f"Recorded {name} -> ({x},{y})")
        time.sleep(0.2)
    out.write_text(json.dumps(coords, indent=2))
    print('Saved layout to', out)
    return coords


def load_layout(path=LAYOUT_PATH):
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f'Layout file not found: {p} — run calibrate first')
    return json.loads(p.read_text())


def click_at(pos):
    x,y = pos
    pyautogui.moveTo(x, y, duration=0.08)
    pyautogui.click()
    time.sleep(0.05)


def run_sequence(seqfile, layout=None, delay_between_chars=0.1):
    layout = load_layout(layout) if layout is None else layout
    seq = Path(seqfile).read_text().splitlines()
    for ln in seq:
        ln = ln.strip()
        if not ln or ln.startswith('#'):
            continue
        if ln.startswith('SET'):
            parts = ln.split()
            if len(parts) >= 2:
                bits = parts[1].strip()
                # bits expected as SW0..SW7 order (LSB first)
                if len(bits) != 8:
                    print('Unexpected bits length:', bits)
                    continue
                print('Setting switches to', bits)
                # assume switches start OFF; click SWi for each bit==1
                for i,ch in enumerate(bits):
                    if ch == '1':
                        name = f'SW{i}'
                        if name not in layout:
                            print('Missing', name, 'in layout')
                            continue
                        click_at(layout[name])
                time.sleep(delay_between_chars)
        elif ln.startswith('STROBE'):
            print('Strobing...')
            click_at(layout['STROBE'])
            time.sleep(delay_between_chars)
        else:
            # allow lines like 'SET 0101' or comments
            print('Ignoring line:', ln)


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    cmd = sys.argv[1]
    if cmd == 'calibrate':
        calibrate()
    elif cmd == 'run':
        if len(sys.argv) < 3:
            print('Usage: logisim_driver.py run input_sequence.txt')
            sys.exit(1)
        seq = sys.argv[2]
        print('Starting sequence run in 3 seconds, switch all switches OFF now')
        time.sleep(3)
        run_sequence(seq)
    else:
        print('Unknown command:', cmd)
        sys.exit(1)
